### ISSUE TITLE
Auto-focus search bar on load

### ISSUE THREAD

**Issue by crenwick** [alexis-jaksone/new-tab#1]
Is there a way to enable auto-focusing the search bar when I open a new tab?

The FAQs states:
> To search just type a phrase in the address-bar and hit the Enter key. This is exactly what the original new tab does.

However, the original new tab auto-focuses while this does not.

**Comment by crenwick** [comment]
Reinstalled this addon and the desired behavior seems to be working... ¯\_(ツ)_/¯

**Comment by crenwick** [comment]
After ~24hrs, this 'bug' came back. Not sure how to fix it, without disabling the add-on completely.

**Comment by alexis-jaksone** [comment]
This is not something that I can fix. The search box is supposed to have this auto-focusing feature. WebExtensions do not have the power to interact with elements outside the page and hence it is not possible to trigger a focus event for the search box from the extension side. You need to report this to Bugzilla.

Since mine works as expected, I would say try the extension on a clean profile to make sure this is not an issue related to a profile damage case.
